# ---------- Build Stage ----------
FROM maven:3.9.9-amazoncorretto-21 AS builder

WORKDIR /app

COPY . .

RUN mvn clean package -DskipTests


# ---------- Runtime Stage ----------
FROM amazoncorretto:21

WORKDIR /app

COPY --from=builder /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
