app.config.loaded=yes
spring.application.name=mbh_api
server.port=8080
logging.level.org.springframework.mongodb.core.MongoTemplate=DEBUG

#! use when running locally, but not on live deployment
# spring.config.import=optional:file:backend/.env[.properties]  

#! works on live deployment, but not locally
# spring.config.import=optional:file:.env[.properties]  

spring.mongodb.uri=${SPRING_MONGODB_URI}
spring.mongodb.database=${SPRING_MONGODB_DATABASE}