name: Deploy Frontend to S3

on:
  push:
    branches:
      - working_branch
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: In
